# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-08-24 21:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0002_auto_20151216_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='islocal',
            field=models.NullBooleanField(default=None),
        ),
    ]
